services:
  momentum-nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@momentum-db:5432/momentum
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_ZXhwZXJ0LWNyYXlmaXNoLTk3LmNsZXJrLmFjY291bnRzLmRldiQ
      - CLERK_SECRET_KEY=sk_test_H3luKwWppPY4hTP2BSfd59j50kQoSh5pjUU7Pr67nk
      - NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
      - NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard
      - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard
      - GOOGLE_CLIENT_ID=your_google_client_id_here
      - GOOGLE_CLIENT_SECRET=your_google_client_secret_here
      - GOOGLE_REDIRECT_URI=http://localhost:3000/settings?integration=google_calendar
      - ENCRYPTION_KEY=V3Q65/KUm+7FJe+W6nxMyh4YygJl2m/3
      - OLLAMA_API_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3
      - DEFAULT_AI_PROVIDER=OLLAMA
    depends_on:
      - momentum-db
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./prisma:/app/prisma
      - ./start.sh:/app/start.sh
      - /app/node_modules
      - /app/.next

  momentum-db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=momentum
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 